---
- name: (RedHat) Ensure MySQL will use a unix socket
  template:
    src: etc/my.cnf.d/mysqld_socket.cnf.j2
    dest: "{{ mysql_config_include_dir }}/mysqld_socket.cnf"
    owner: root
    group: root
    mode: "0644"
  notify: restart mysql
  when: ansible_os_family|lower == "redhat"

- name: Create slow query log file (if configured)
  file:
    path: "{{ mysql_slow_query_log_file }}"
    state: touch
    owner: mysql
    group: "{{ mysql_log_file_group }}"
    mode: "0640"
    modification_time: preserve
    access_time: preserve
  notify: restart mysql
  when:
    - mysql_slow_query_log_enabled is defined
    - mysql_slow_query_log_enabled|bool

- name: Configre MySQL InnoDB Settings
  template:
    src: etc/my.cnf.d/innodb.cnf.j2
    dest: "{{ mysql_config_include_dir }}/innodb.cnf"
    owner: root
    group: root
    mode: "0644"
  notify: restart mysql
