---
- name: (Debian) Install required repo management packages
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - gpg
      - software-properties-common
    cache_valid_time: "3600"
    force_apt_get: true
    state: present
    update_cache: true
  when: ansible_os_family == "Debian"

- name: (Debian) Add official MariaDB repo signing key
  apt_key:
    url: https://mariadb.org/mariadb_release_signing_key.asc
    state: present
  when: ansible_os_family == "Debian"

- name: (Debian) Add official MariaDB repo
  apt_repository:
    repo: >-
      deb [arch=amd64] https://ftp.osuosl.org/pub/mariadb/repo/{{-
      mysql_version }}/{{ ansible_distribution|lower }}
      {{ ansible_distribution_release.split(" ")[0]|lower }} main
    state: present
  when: ansible_os_family == "Debian"

- name: (Debian) Update APT cache
  apt:
    force_apt_get: true
    cache_valid_time: "3600"
    state: present
    update_cache: true
  when: ansible_os_family == "Debian"

- name: (RedHat) Add official MariaDB repo
  yum_repository:
    name: MariaDB
    description: MariaDB {{ mysql_version }} CentOS repository
    baseurl: >-
      http://yum.mariadb.org/{{ mysql_version }}/centos{{-
      ansible_distribution_major_version -}}-amd64/
    gpgkey: https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
    gpgcheck: true
    state: present
  when: ansible_os_family == "RedHat"
