---
- name: (Debian) Install python3-apt package
  package:
    name: python3-apt
    state: present
  when: ansible_os_family|lower == "debian"

- name: Gather package facts
  package_facts:
    manager: auto

- name: Set and sanitize systemd version facts
  set_fact:
    systemd_version: >-
      {{ ansible_facts.packages['systemd'][0].version }}

- name: Creates service directory
  file:
    path: /etc/systemd/system/{{ mysql_daemon }}.service.d
    state: directory

- name: Create service file
  template:
    src: etc/systemd/restart.conf.j2
    dest: /etc/systemd/system/{{ mysql_daemon }}.service.d/restart.conf
    owner: root
    group: root
    mode: 0600
  notify: restart mysql
