---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: "molecule-ansible-role-mysql"
    image: ${MOLECULE_IMAGE:-ghcr.io/artis3n/docker-almalinux8-ansible:latest}
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: false


provisioner:
  name: ansible
  options:
    extra-vars: "{'mysql_innodb_buffer_pool_size': '256M'}"
      
verifier:
  name: ansible
