---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: "molecule-ansible-role-mysql"
    image: "${MOLECULE_IMAGE:-geerlingguy/docker-centos8-ansible:latest}"
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true


provisioner:
  name: ansible
  config_options:
    defaults:
      callback_enabled: timer
      internal_poll_interval: "0.01"
      nocows: 1
      var_compression_level: 9
    diff:
      always: true
  log: true

verifier:
  name: ansible
