---
- name: (RedHat) Add official MariaDB repo
  yum_repository:
    name: MariaDB
    description: MariaDB {{ mysql_version }} CentOS repository
    baseurl: >-
      http://yum.mariadb.org/{{ mysql_version }}/centos{{-
      ansible_distribution_major_version -}}-amd64/
    gpgkey: https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
    gpgcheck: true
    state: present
    module_hotfixes: true
  when: ansible_os_family|lower == "redhat"
