name: Ansible Molecule Pipeline

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:
    branches: [master]

env:
  # https://www.jeffgeerling.com/blog/2020/getting-colorized-output-molecule-and-ansible-on-github-actions-ci
  PY_COLORS: '1'
  ANSIBLE_FORCE_COLOR: '1'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - image: centos8
          - image: debian10
            command: /lib/systemd/systemd
          - image: debian11
            command: /lib/systemd/systemd
          - image: ubuntu1804
            command: /lib/systemd/systemd
          - image: ubuntu2004
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - run: pip3 install --user -r requirements.txt
      - run: molecule test
        env:
          MOLECULE_IMAGE: ${{ matrix.image }}
          MOLECULE_COMMAND: ${{ matrix.command }}

  test-legacy:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - image: geerlingguy/centos7
            command: /usr/lib/systemd/systemd
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - run: pip3 install --user -r requirements.txt
      - run: molecule test
        env:
          MOLECULE_IMAGE: ${{ matrix.image }}
          MOLECULE_COMMAND: ${{ matrix.command }}
